### ISSUE TITLE
checks.yml repo linter requires token

### ISSUE THREAD

**Issue by JosephGasiorekUSDS** [DSACMS/repo-scaffolder#116]
## Issue Report

module-name: checks.yml repo linter requires token

### Expected behavior

To be able to run the `repo-scaffolder` [setup procedure for existing repos](https://github.com/DSACMS/repo-scaffolder?tab=readme-ov-file#existing-projects) and have the checks work.

### Actual behavior

The checks.yml workflow is set to run on pull requests. It then runs the `newrelic/repolinter-action@v1` action with the `output_type` configuration set to `issue` instead of `exit-code`. The `repolinter-action` [configuration](https://github.com/newrelic/repolinter-action/tree/main?tab=readme-ov-file#inputs) requires a `token` value to be set with a valid Github Personal access token.

### Steps to reproduce the behavior

Run the steps on an existing repo and and the checks won't pass. In my case the error message was:
```
Error: A fatal error was thrown.
Error: Octokit API call failed. This may be due to your token permissions or an issue with the GitHub API. If the error persists, feel free to open an issue.
Error: GET https://api.github.com/repos/XXXXX/XXXX/issues?creator=app%2Fgithub-actions&labels=cms-oss-tier4&state=all&sort=created&direction=desc returned status 403
```

I filed an issue instead of a PR as I was unsure of the preferred solution. Possible solutions include:
 - the `output_type` could be set to `exit-code`
 - add more steps to the setup procedure to create a token, add it to the secrets with the appropriate name

**Comment by natalialuzuriaga** [comment]
Closing, resolved in #130
