### ISSUE TITLE
Repometrics: Remove Maturity Model question and add tier number directly to code.json

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#118]
## Issue Report

Repometrics: Remove Maturity Model question and add tier number directly to code.json

### Expected behavior
- maturity_model_tier field value is already in code.json
- No question in cookiecutter asking user to select maturity model

### Actual behavior
- Currently in cookiecutter, we ask the user to select maturity model. There is a chance users can pick the wrong maturity model.
- Based on number selected, it is stored in the maturity_model_tier variable in code.json

### Fix
- Replace `cookiecutter.maturity_model_tier` with tier number: https://github.com/DSACMS/repo-scaffolder/blob/0a44dc5a6c4c6c47c8a128efc8e02e051c0c312d/tier3/%7B%7Bcookiecutter.project_slug%7D%7D/repometrics/%7B%7Bcookiecutter.project_type%7D%7D/code.json#L9
- Remove maturity_model_tier question in cookiecutter.json

**Comment by RicardoZamora01** [comment]
PR created #126 !

**Comment by decause-gov** [comment]
08/02:
- PR has been merged! https://github.com/DSACMS/repo-scaffolder/pull/126
