### ISSUE TITLE
code.json: Add required fields from code.json and publiccode.yml to repometrics cookiecutter

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#124]
## MENTOR
- @natalialuzuriaga 
- USDC SWE Fellow, OSPO
- Slack

## BRIEF DESCRIPTION

After Natalia's research sprint on code.json and publiccode.yml, we have decided to update the CMS code.json to include required fields from code.json and publiccode.yml so that we can comply with both metadata standards. This rotation is focused on adding these new fields to repometrics and using cookiecutter to populate as many of the fields as possible.

- Mural with comparison of code.json + publiccode.yml fields: https://app.mural.co/t/ccs9461/m/ccs9461/1720012298215/591f89739a9a842d37e1b7508d4f14c17fe7e740?sender=ubadd8a347114498c913e6865
- Google Planning Doc: https://docs.google.com/document/d/1gYLvfoyUT4Db3TyL9EPQAgePk_q6KSFPX0LHcccewd8/edit

## SCOPING
- 1 week

## SKILLS NEEDED
Python, Cookiecutter

## REQUIRED DELIVERABLES
Make as clear of a step-by-step list as you can:
1. Natalia will make a table with the list of all required fields in the Google Doc
EDIT: this is done! https://docs.google.com/document/d/1gYLvfoyUT4Db3TyL9EPQAgePk_q6KSFPX0LHcccewd8/edit#heading=h.ez3m3cjembkv
2. Identify fields can be populated using cookiecutter vs can be automatically filled out using GitHub API in post_gen_project.py
3. Add fields to cookiecutter.

## DESIRED DELIVERY WINDOW
- August

## NOTES/INSPO
Super super excited for this one 🥳 

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [X] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [X] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [X] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by IsaacMilarky** [comment]
9/30:

- Labor hours hacksesh scheduled for tomorrow 10/1
- We will talk about the date created logic as well as the labor hours logic and code.json broadly

**Comment by IsaacMilarky** [comment]
10/4:

- @sachin-panayil fixed issue with default date being removed: https://github.com/DSACMS/repo-scaffolder/pull/165
- @IsaacMilarky created labor hours calculation: https://github.com/DSACMS/repo-scaffolder/pull/157
- @sachin-panayil created the date calculation for age and date created of project. 
- Update the rest once @natalialuzuriaga gets back from GHC

**Comment by natalialuzuriaga** [comment]
10/07:
- All PRs have been merged. Main is updated with all changes
