### ISSUE TITLE
Outbound Checklists: Convert from PDF to Markdown

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#147]
## MENTOR
- @natalialuzuriaga  
- SWE Fellow, USDigitalCorps
- dm on slack, #wg-government on CHAOSS.community slack, 

## BRIEF DESCRIPTION
Currently, all our outbound checklists are in a pdf format. We would like to have a markdown file of it on the repository for easy access and to be able to reference to specific sections

## SCOPING
- 1 week

## SKILLS NEEDED
Markdown, Git/GitHub

## REQUIRED DELIVERABLES
- Convert Tier 1 Checklist to markdown: https://github.com/DSACMS/repo-scaffolder/blob/main/tier1/checklist.pdf
- Convert Tier 2 Checklist to markdown: https://github.com/DSACMS/repo-scaffolder/blob/main/tier2/checklist.pdf
- Convert Tier 3 Checklist to markdown: https://github.com/DSACMS/repo-scaffolder/blob/main/tier3/checklist.pdf
- Convert Tier 4 Checklist to markdown: https://github.com/DSACMS/repo-scaffolder/blob/main/tier4/checklist.pdf

## DESIRED DELIVERY WINDOW
- Before Sept 16

## NOTES/INSPO
Any feedback and ideas on this issue are welcome!

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [x] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [x] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [x] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by natalialuzuriaga** [comment]
09/16:
Hack Sesh complete ✅ 

Next steps:

Hey @g5t3, let's start off with focusing on the Tier 1 checklist.
First, let's create the markdown file for the Tier 1 checklist. In the tier1 folder/directory, create a new file called checklist.md
In checklist.md you can start writing the markdown code in there. 

Let me know if you have any questions as you work on this!

It is probably best to start off with the "Code Review" section (page 4). Some pages are more complex than others so if you get stuck and I'm taking too long to help/respond to you, feel free to jump around and do other sections.

Important links:
Ticket on the project board: https://github.com/DSACMS/repo-scaffolder/issues/147
Tier 1 PDF on repo: https://github.com/DSACMS/repo-scaffolder/blob/main/tier1/checklist.pdf
Tier 1 Checklist Google Doc: https://docs.google.com/document/d/1EwjLpAOChNLLHSAnXdHQCtzcrcsdqsf1WcS_ZjNDClQ/edit#heading=h.slv8bucc4nti

**Comment by IsaacMilarky** [comment]
9/30:

- Jabir merged PR to create Tier 1 checklist in markdown: https://github.com/DSACMS/repo-scaffolder/pull/150
- @NoobNoob06 is still working on their changes for Tier 3
- Will then work on 2 and 4 after 3 is done 🚢

**Comment by IsaacMilarky** [comment]
10/4:

- Some feedback from @IsaacMilarky and @natalialuzuriaga 
- Will work on and hopefully fix soon
- Should not have too much trouble for tiers 2 and 4
- Will have tier 3 done by today 
- Some minor link issues and grammar stuff

**Comment by natalialuzuriaga** [comment]
10/07:
- Keni has completed the Tier 3 checklist conversion
- Working on Tier 2 and Tier 4

**Comment by IsaacMilarky** [comment]
10/11:

- Tier 2 should be in by EoD today will send a PR
- Busy week this week

**Comment by IsaacMilarky** [comment]
10/15:

- Markdown checklist for tier 2 is up in PR: https://github.com/DSACMS/repo-scaffolder/pull/178
- Needs some minor changes due to 2 broken links (one for code.gov and one for cms.github.gov)
- Overall great work !

**Comment by decause-gov** [comment]
10/21:
- All the tier PRs have been filed
- Tier 3: https://github.com/DSACMS/repo-scaffolder/tree/tier3-checklist-markdown
- Tier2 is approved, may not be merged yet: https://github.com/DSACMS/repo-scaffolder/tree/tier2-checklist-markdown
- Tier4 is ready for review: https://github.com/DSACMS/repo-scaffolder/tree/tier4-checklist-markdown
- ACTION: @DSACMS/ospo Plz review the PRs for @NoobNoob06

**Comment by decause-gov** [comment]
10/25:
- All PRs have been Merged!!! 
- Congrats @NoobNoob06 🎉
