### ISSUE TITLE
Code.json: Add usageType and exemptionText

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#162]
`usageType` is a required field in code.json and I completely missed this oops. Let's add this to code.json and cookiecutter.
Refer to DHS SCIP for more information: https://www.dhs.gov/scip

**Comment by natalialuzuriaga** [comment]
code.json schema:
- https://github.com/GSA/code-gov-data/blob/master/schemas/schema-2.0.0.json

**Comment by IsaacMilarky** [comment]
10/11:

- Backburner until @natalialuzuriaga gets back 
- PR link: https://github.com/DSACMS/repo-scaffolder/pull/174

**Comment by IsaacMilarky** [comment]
10/15:

- Backburner until @natalialuzuriaga gets back

**Comment by decause-gov** [comment]
10/21:
- ACTION: @natalialuzuriaga will review the PR EoB

**Comment by decause-gov** [comment]
10/25:
- All merged. Donezo 🎉
