### ISSUE TITLE
Add README.md file for this repository explaining what repo-scaffolder is for

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/repo-scaffolder#18]
## Issue Report

Add missing README.md

### Expected behavior

If we're going to require all our other repos to include a README.md file, that would include this repo as well ;)

### Actual behavior

README.md does not exist.

### Steps to reproduce the behavior

This project should be considered a Tier2 or Tier3 project, and utilize a corresponding README.md as such.

**Comment by natalialuzuriaga** [comment]
README.md for the repository has been created!
