### ISSUE TITLE
code.json: Bug when generating date created field value

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#181]
**Describe the bug**
When I use repo-scaffolder to create a fresh new repository and then use the cookiecutter command to create the repo's code.json file, the "created" field in the date object is incorrect.

**To Reproduce**
1. For any tier. create a new repository using cookiecutter/repo-scaffolder
2. Use the cookiecutter command to create the repo's code.json file.
3. The "created" field in the date object is set to "2023-10-05T14:06:51-04:00".

**Expected behavior**
The created field should be set to the date the repository is created / the repository's first commit. It looks like it is being set to the first commit of the repo template I believe?

**Screenshots**
In code.json
<img width="456" alt="Screenshot 2024-10-21 at 3 25 37 PM" src="https://github.com/user-attachments/assets/5df992ce-97d0-4320-810c-3000dea626cc">

**Additional context**
Related to #153

**Comment by sachin-panayil** [comment]
10/23:
- Created a PR to fix with this: https://github.com/DSACMS/repo-scaffolder/pull/185
- Nat and I tackled this together!

**Comment by natalialuzuriaga** [comment]
Merged! Closing issue
