### ISSUE TITLE
code.json: labor_hour value taking into account markdown files

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#196]
**Describe the bug**
Overall, labor_hour value is pretty high because it is taking into account the markdown files. We would like to exclude this from the calculation.

**To Reproduce**
1. Create a new repository using repo-scaffolder. Do not create new files or add lines of code to the repo.
2. Go to `.github`
3. Run `cookiecutter . --directory=codejson` to generate code.json
4. Answer prompts
5. labor_hours result value should be ~2,000. This is not an accurate reflection of the amount of work/hours/effort put into the repository.

**Expected behavior**
We want the labor_hours result to exclude the documentation markdown files (README.md, MAINTAINERS.md, etc.) and other templates files. labor_hours should reflect the new files and lines of code that the project team has added to the repository.

**Comment by sachin-panayil** [comment]
idea for this could be to run the labor_hour logic in a pre_gen file
