### ISSUE TITLE
Contact email not slugified in Cookie Cutter for COMMUNITY_GUIDELINES.md

### ISSUE THREAD

**Issue by vantuyls** [DSACMS/repo-scaffolder#36]
## Issue Report

in 

https://github.com/DSACMS/repo-scaffolder/blob/main/tier1/%7B%7Bcookiecutter.project_slug%7D%7D/COMMUNITY_GUIDELINES.md

we have a pseudo-slug for {contact email} that needs to be properly slugified for all versions of COMMUNITY_GUIDELINES.md at all tiers

**Comment by natalialuzuriaga** [comment]
Closing since updates has been made to COMMUNITY_GUIDELINES.md
