### ISSUE TITLE
CODEOWNERS.md at all tiers needs to be slugified

### ISSUE THREAD

**Issue by vantuyls** [DSACMS/repo-scaffolder#37]
**Is your feature request related to a problem? Please describe.**
Currently, the [cookiecutter CLI](https://github.com/DSACMS/repo-scaffolder/blob/main/tier1/cookiecutter.json) asks for basic information about the repository. There is an opportunity to collect more information about code owners and add more variables to`cookiecutter.json`s to populate CODEOWNERS.md.

**Describe the intended behavior**
The CLI tool asks a series of questions and collects responses from the user. The responses are then populated into CODEOWNERS.md upon repository creation.

**Describe the solution you'd like**
Some variables that can be added include but are not limited to:
- Usernames of code owners
- Repo Domains

Steps to completion:
- Review current cookiecutter questions and CODEOWNERS.md across all tiers.
- Identify potential variables to add. Consider whether there are tier-specific variables. Get list approved by team.
- Add new variables to cookiecutter.json and templates. Populate fields accordingly during repository creation.

**Comment by decause-gov** [comment]
06/17:
- Met with team, decided to split tickets.
- Question: repo_domain in cookiecutter. let's do if logic? (Do you want more than one domain of codewoners? Y/N. "Do you have Front-end?") Explore the github API for pulling teams information and adding users.)
- ACTION: Dicuss this more sync or async in slack huddle.

**Comment by natalialuzuriaga** [comment]
06/17:
- Brandon: Only have a variable to collect the list of usernames
- Nat: No longer sluggifying repo domains, instead we will have guidance/docs for this: provide domain examples, using github child teams feature

**Comment by decause-gov** [comment]
06/21:
- PR is Open: https://github.com/DSACMS/repo-scaffolder/pull/100 💯 
- ACTION: @natalialuzuriaga @IsaacMilarky @decause-gov plz review 💯

**Comment by decause-gov** [comment]
06/24:
- PR Merged!
- Nice work @Firebird1029 🔥 🐦 💯
