### ISSUE TITLE
MAINTAINERS.md needs to be properly slugified at all tiers

### ISSUE THREAD

**Issue by vantuyls** [DSACMS/repo-scaffolder#38]
**Is your feature request related to a problem? Please describe.**
Currently, the [cookiecutter CLI](https://github.com/DSACMS/repo-scaffolder/blob/main/tier1/cookiecutter.json) asks for basic information about the repository. There is an opportunity to collect more information about maintainers and add more variables to`cookiecutter.json`s to populate MAINTAINERS.md.

**Describe the intended behavior**
The CLI tool asks a series of questions and collects responses from the user. The responses are then populated into MAINTAINERS.md upon repository creation.

**Describe the solution you'd like**
Some variables that can be added include but are not limited to:
- Maintainers: Name, github username, role (reviewer, approver, maintainer)

Steps to completion:
- Review current cookiecutter questions and MAINTAINERS.md across all tiers.
- Identify potential variables to add. Consider whether there are tier-specific variables. Get list approved by team.
- Add new variables to cookiecutter.json and templates. Populate fields accordingly during repository creation.

**Comment by decause-gov** [comment]
06/17:
- Met and discussed. Nick will take MAINTAINERS.md, and Brandon will take CODEOWNERS.md
- goal: finish this ticket before EoW!
- Question: repo_domain in cookiecutter. let's do if logic? (Do you want more than one domain of codewoners? Y/N. "Do you have Front-end?") Explore the github API for pulling teams information and adding users.)
- ACTION: Dicuss this more sync or async in slack huddle.

**Comment by CreativeNick** [comment]
Idea: Have two lists: "Current maintainers" and "Emeritus (aka retired) maintainers"

**Comment by decause-gov** [comment]
@CreativeNick Plz update upon your return

**Comment by CreativeNick** [comment]
**Pull request:** https://github.com/DSACMS/repo-scaffolder/pull/104

Did some research on JINJA2 and CLI automation, may require some automation to help streamline the maintainers process. Will need to ask during meeting about how `cookiecutter.json` works with `MAINTAINERS.md` in more detail.

**Comment by natalialuzuriaga** [comment]
06/24:
- PR up for review: https://github.com/DSACMS/repo-scaffolder/pull/104
- Update Tier 4, remove from cookiecutter.json in root dir
- Test on command line
- Meeting with Nat for deep dive on repo-scaffolder

**Comment by IsaacMilarky** [comment]
6/28
- Issue with 'secrets not defined' after entering prompts
- ACTION: file issue for above @natalialuzuriaga 
- ACTION: create a new PR and close the old one

**Comment by IsaacMilarky** [comment]
7/1:

- Still finishing up, need to create actual branch
- Pretty much done
- ACTION: Continue work 
- USDS filled a PR! https://github.com/DSACMS/repo-scaffolder/pull/107

**Comment by CreativeNick** [comment]
7/1:
- New PR created: https://github.com/DSACMS/repo-scaffolder/pull/110
- Waiting for feedback/review

**Comment by IsaacMilarky** [comment]
7/8:

- Merged
