### ISSUE TITLE
IDEA: GH Action to generate tree + incorporate in repo-scaffolder

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/repo-scaffolder#60]
**Is your feature request related to a problem? Please describe.**
Tier 3 & Tier 4 README.md includes a Repository Structure section. Currently, our users must do this manually, however this is an opportunity to automate this upon README.md file creation by creating a GitHub action that uses the tree command.

**Describe the intended behavior**
Upon the creation of the README.md file, the repository structure is automatically generated using the `tree` command.

**Describe the solution you'd like**
Create a GitHub action that uses the tree command to generate the repository structure section of the README.md.

**Comment by natalialuzuriaga** [comment]
07/19:
- Just started!

**Comment by decause-gov** [comment]
7/22:
- Preliminary gh-action script exists. Getting stuck on esaping newlines. Tree command has new-lines, but transferring to SED is complex.
- IDEA: Ask chatgpt to write a sed/awk command to do this?
- IDEA: use `man tree` to explore the 'graphics' options that might help with whitespace/newlines.
- Goal: Ship this week!

**Comment by Firebird1029** [comment]
PR ready for review here: https://github.com/DSACMS/repo-scaffolder/pull/123

**Comment by decause-gov** [comment]
07/26:
- PR has been merged! #123 🚢 🌲
